---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: copy main /etc/hosts file to all servers
      copy:
        src: /etc/ansible/files/main-hosts
        dest: /etc/hosts

## Author: Jake Walters
## Command: ansible-playbook -i inventory/list-of-hosts.txt playbooks/homelab/hosts-file.yml
## Purpose: manage hosts file for homelab
