---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: copy main /etc/resolv.conf file to all servers
      copy:
        src: /etc/ansible/files/resolv-conf
        dest: /etc/resolv.conf
        owner: root
        group: root

## Author: Jake Walters
## Command: ansible-playbook -i inventory/list-of-hosts.txt playbooks/homelab/resolv-conf.yml
## Purpose: keeps /etc/resolv.conf the same in my homelab
