---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: collect files
    find:
      paths: "/var/crash"
      age: 30d
      recurse: True
      # file_type: any  # Added in ansible 2.3
    register: collected_files

  - name: collect directories
    find:
      paths: "/var/crash"
      patterns: '127.0.0.1'
      age: 30d
      recurse: True
      file_type: directory
    register: collected_directories

  - name: remove collected files and directories
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: >
      {{
        collected_files.files
        + collected_directories.files
      }}

## Author: Jake Walters
## Command: ansible-playbook -i inventory/list-of-hosts.txt playbooks/file-directory-cleanup.yml
## Purpose: keep the crash dir in /var clean
